#include "Formateur.h"

#include <QDate>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QVariant>
#include <QDebug>

Formateur::Formateur()
    : m_id(-1)
    , m_dateEmbauche(QDate::currentDate())
{
}

Formateur::Formateur(int id,
                     const QString &nom,
                     const QString &prenom,
                     const QString &email,
                     const QString &telephone,
                     const QString &specialite,
                     const QDate &dateEmbauche,
                     const QString &status)
    : m_id(id)
    , m_nom(nom)
    , m_prenom(prenom)
    , m_email(email)
    , m_telephone(telephone)
    , m_specialite(specialite)
    , m_dateEmbauche(dateEmbauche)
    , m_status(status)
{
}

int Formateur::id() const { return m_id; }
QString Formateur::nom() const { return m_nom; }
QString Formateur::prenom() const { return m_prenom; }
QString Formateur::email() const { return m_email; }
QString Formateur::telephone() const { return m_telephone; }
QString Formateur::specialite() const { return m_specialite; }
QDate Formateur::dateEmbauche() const { return m_dateEmbauche; }
QString Formateur::status() const { return m_status; }

void Formateur::setId(int id) { m_id = id; }
void Formateur::setNom(const QString &nom) { m_nom = nom; }
void Formateur::setPrenom(const QString &prenom) { m_prenom = prenom; }
void Formateur::setEmail(const QString &email) { m_email = email; }
void Formateur::setTelephone(const QString &telephone) { m_telephone = telephone; }
void Formateur::setSpecialite(const QString &specialite) { m_specialite = specialite; }
void Formateur::setDateEmbauche(const QDate &dateEmbauche) { m_dateEmbauche = dateEmbauche; }
void Formateur::setStatus(const QString &status) { m_status = status; }

bool Formateur::createTable(const QSqlDatabase &database)
{
    if (!database.isOpen()) {
        return false;
    }
    QString sql = "CREATE TABLE FORMATEUR ("
                  "ID_FORMATEUR NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                  "NOM VARCHAR2(100), "
                  "PRENOM VARCHAR2(100), "
                  "EMAIL VARCHAR2(150), "
                  "TELEPHONE VARCHAR2(50), "
                  "SPECIALITE VARCHAR2(100), "
                  "DATE_EMBAUCHE DATE, "
                  "STATUS VARCHAR2(50))";
    QSqlQuery query(database);
    return query.exec(sql);
}

bool Formateur::ensureAutoIncrement(const QSqlDatabase &database)
{
    if (!database.isOpen()) {
        return false;
    }

    QSqlQuery query(database);
    if (!query.exec("SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_FORMATEUR'")) {
        qWarning() << "Unable to check FORMATEUR sequence:" << query.lastError().text();
        return false;
    }
    if (query.next()) {
        return true;
    }

    int startValue = 1;
    if (query.exec("SELECT NVL(MAX(ID_FORMATEUR), 0) + 1 FROM FORMATEUR")) {
        if (query.next()) {
            startValue = query.value(0).toInt();
        }
    }

    QString seqSql = QString("CREATE SEQUENCE SEQ_FORMATEUR START WITH %1 INCREMENT BY 1").arg(startValue);
    if (!query.exec(seqSql)) {
        qWarning() << "Unable to create FORMATEUR sequence:" << query.lastError().text();
        return false;
    }

    QString trigSql =
        "CREATE OR REPLACE TRIGGER TRG_FORMATEUR_ID "
        "BEFORE INSERT ON FORMATEUR "
        "FOR EACH ROW "
        "BEGIN "
        "SELECT SEQ_FORMATEUR.NEXTVAL INTO :NEW.ID_FORMATEUR FROM DUAL; "
        "END;";
    if (!query.exec(trigSql)) {
        qWarning() << "Unable to create FORMATEUR trigger:" << query.lastError().text();
        return false;
    }

    return true;
}

bool Formateur::insert(const QSqlDatabase &database) const
{
    if (!database.isOpen()) {
        return false;
    }

    QSqlQuery query(database);
    query.prepare("INSERT INTO FORMATEUR (NOM, PRENOM, EMAIL, TELEPHONE, SPECIALITE, DATE_EMBAUCHE, STATUS) "
                  "VALUES (:nom, :prenom, :email, :telephone, :specialite, :dateEmbauche, :status)");
    query.bindValue(":nom", m_nom);
    query.bindValue(":prenom", m_prenom);
    query.bindValue(":email", m_email);
    query.bindValue(":telephone", m_telephone);
    query.bindValue(":specialite", m_specialite);
    query.bindValue(":dateEmbauche", m_dateEmbauche);
    query.bindValue(":status", m_status);

    bool ok = query.exec();
    if (!ok) {
        qWarning() << "Formateur insert failed:" << query.lastError().text();
    }
    return ok;
}

bool Formateur::update(const QSqlDatabase &database) const
{
    if (!database.isOpen() || m_id < 0) {
        return false;
    }

    QSqlQuery query(database);
    query.prepare("UPDATE FORMATEUR SET NOM = :nom, PRENOM = :prenom, EMAIL = :email, TELEPHONE = :telephone, "
                  "SPECIALITE = :specialite, DATE_EMBAUCHE = :dateEmbauche, STATUS = :status WHERE ID_FORMATEUR = :id");
    query.bindValue(":nom", m_nom);
    query.bindValue(":prenom", m_prenom);
    query.bindValue(":email", m_email);
    query.bindValue(":telephone", m_telephone);
    query.bindValue(":specialite", m_specialite);
    query.bindValue(":dateEmbauche", m_dateEmbauche);
    query.bindValue(":status", m_status);
    query.bindValue(":id", m_id);

    bool ok = query.exec();
    if (!ok) {
        qWarning() << "Formateur update failed:" << query.lastError().text();
    }
    return ok;
}

bool Formateur::remove(const QSqlDatabase &database) const
{
    if (!database.isOpen() || m_id < 0) {
        return false;
    }

    QSqlQuery query(database);
    query.prepare("DELETE FROM FORMATEUR WHERE ID_FORMATEUR = :id");
    query.bindValue(":id", m_id);

    bool ok = query.exec();
    if (!ok) {
        qWarning() << "Formateur delete failed:" << query.lastError().text();
    }
    return ok;
}
